

# loadbalancer.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80         # Port exposed outside the cluster
      targetPort: 8080 # Port your app listens on within the container
